# coding=utf-8

APPLY_MODEL = 'APPLY_MODEL'
CREATE_MODEL = 'CREATE_MODEL'
DISPLAY_DATA = 'DISPLAY_DATA'
DISPLAY_SCHEMA = 'DISPLAY_SCHEMA'
INFER_SCHEMA = 'INFER_SCHEMA'
SAVE_MODEL = 'SAVE_MODEL'
SAVE_DATA = 'SAVE_DATA'
SAVE_VISUALIZATION = 'SAVE_VISUALIZATION'
