from textwrap import dedent

from juicer.spark.vis_operation import HtmlVisModel


class BaseHtmlReport(object):
    pass


class EvaluateModelOperationReport(BaseHtmlReport):
    """ Report generated by class EvaluateModelOperation """

    @staticmethod
    def generate_visualization(**kwargs):
        evaluator = kwargs['evaluator']
        metric_value = kwargs['metric_value']
        title = kwargs['title']
        operation_id = kwargs['operation_id']
        task_id = kwargs['task_id']
        
        all_params = ['<tr><th>{}</th><td><em>{}</em></td></tr>'.format(x.name, x.doc) \
                         for x in evaluator.extractParamMap()]
	 
        vis_model = dedent('''
            <table class="table table-bordered table-striped table-condensed" style="width:100%">
              <thead>
                <tr>
                  <th colspan="2">{title}</th>
                </tr>
              <thead>
              <tbody>
                <tr>
                  <th>{metric}</th>
                  <td>{value}</td>
                </tr>
                <tr>
                  <th colspan="2">Execution parameters
                  </th>
                </tr>
                {params}
            </table>
        ''').format(title=title, metric=evaluator.getMetricName(),
                    value=metric_value, params=''.join(all_params))

        return HtmlVisModel(
            vis_model, task_id, operation_id, 'EvaluateModelOperation', title,
            '[]', '', '', '', {})
