from textwrap import dedent

from juicer.spark.vis_operation import HtmlVisModel


class BaseHtmlReport(object):
    pass


class EvaluateModelOperationReport(BaseHtmlReport):
    """ Report generated by class EvaluateModelOperation """

    @staticmethod
    def generate_visualization(**kwargs):
        evaluator = kwargs['evaluator']
        title = kwargs['title']
        operation_id = kwargs['operation_id']
        task_id = kwargs['task_id']
        
	all_params = ['<tr><td>{}</td><td><em>{}</em></td><td>{}</td><td>{}</td></tr>'.format(
            x.name, x.doc, evaluator._paramMap.get(x, 'unset'), evaluator._defaultParamMap.get(x, 'unset')) \
                         for x in evaluator.extractParamMap()] 

        vis_model = dedent('''
            <p>
               <h5>Evaluation result</h5>
            </p>
            <table class="table table-bordered table-striped table-sm" style="width:100%">
              <thead>
                 <tr>
                   <th>Parameter</th>
                   <th>Description</th>
                   <th>Value</th>
                   <th>Default</th>
                 </tr>
              </thead>
              <tbody>
                {params}
              </tbody>
            </table>
        ''').format(title=title, params=''.join(all_params))

        return HtmlVisModel(
            vis_model, task_id, operation_id, 'EvaluateModelOperation', title,
            '[]', '', '', '', {})
